@startuml
!theme vibrant
App --> Hospital
App --> Patient
App --> Doctor
Read_Hospital_Excel_Sheet <-- Hospital
Read_Hospital_Excel_Sheet <-- Doctor
Read_Hospital_Excel_Sheet <-- Patient
Write_Hospital_Excel_Sheet <-- Hospital
Write_Hospital_Excel_Sheet <-- Doctor
Write_Hospital_Excel_Sheet <-- Patient
App : main_menu()
App : admin_mode()
App : user_mode()
Hospital : hospital_department()
Hospital : hospital_doctors()
Hospital : hospital_residents()
Doctor : add_doctor()
Doctor : display_doctor()
Doctor : delete_doctor()
Doctor : edit_doctor()
Doctor : doctor_menu()
Patient : age(birthday)
Patient : add_patient()
Patient : display_patient()
Patient : delete_patient()
Patient : edit_patient()
Patient : patient_menu()
Read_Hospital_Excel_Sheet : Read_Patients_DataBase()
Read_Hospital_Excel_Sheet : Read_Doctors_DataBase()
Write_Hospital_Excel_Sheet : Write_Patients_DataBase(Patients_Database)
Write_Hospital_Excel_Sheet : Write_Doctors_DataBase(Doctors_Database)
@enduml
